name: Build Tekky iOS (.ipa)

on:
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.24.5"
  RUST_VERSION: "1.75"
  VCPKG_COMMIT_ID: "120deac3062162151622ca4860575a33844ba10b"
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

jobs:
  generate-bridge:
    uses: ./.github/workflows/bridge.yml

  build-ios-ipa:
    name: Build iOS Unsigned IPA
    needs: [generate-bridge]
    runs-on: macos-14
    steps:
      - name: Checkout Código Fonte
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Instalar Dependências do Sistema
        run: |
          brew install nasm yasm

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Aplicar Patches do Flutter
        run: |
          cd $(dirname $(dirname $(which flutter)))
          if [[ "3.24.5" == "${{ env.FLUTTER_VERSION }}" ]]; then
            git apply ${{ github.workspace }}/.github/patches/flutter_3.24.4_dropdown_menu_enableFilter.diff || true
          fi

      - name: Configurar VCPKG (Cache do GitHub Actions)
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
          doNotCache: false

      - name: Instalar Dependências VCPKG para iOS (arm64-ios)
        shell: bash
        run: |
          if ! $VCPKG_ROOT/vcpkg \
            install \
            --triplet arm64-ios \
            --x-install-root="$VCPKG_ROOT/installed"; then
            find "${VCPKG_ROOT}/" -name "*.log" | while read -r _1; do
              echo "$_1:"
              echo "======"
              cat "$_1"
              echo "======"
              echo ""
            done
            exit 1
          fi

      - name: Instalar Rust Toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: "aarch64-apple-ios"
          components: "rustfmt"

      - name: Restaurar arquivos da ponte (Bridge)
        uses: actions/download-artifact@v4
        with:
          name: bridge-artifact
          path: ./

      - name: Compilar Biblioteca Nativa Rust para iOS
        run: |
          cargo build --locked --features flutter,hwcodec --release --target aarch64-apple-ios --lib

      - name: Compilar App Flutter para iOS (Sem Assinatura)
        run: |
          cd flutter
          flutter build ios --release --no-codesign

      - name: Empacotar em arquivo .IPA para Sideload
        run: |
          mkdir -p Payload
          cp -r flutter/build/ios/iphoneos/Runner.app Payload/
          zip -r TekkyRemote.ipa Payload
          
      - name: Enviar .ipa para os Artefatos
        uses: actions/upload-artifact@v4
        with:
          name: TekkyRemote-iOS-Unsigned
          path: TekkyRemote.ipa
